import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import { NavBar } from "@/components/nav-bar";
import { Footer } from "@/components/site-footer";
import "./globals.css";
import ProviderWrapper from "../provider-wrapper";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning
        className={`${inter.variable} antialiased`}
      >
        <ProviderWrapper>
          <main className='container min-h-[90vh]'>{children}</main>
          <NavBar />
          <Footer />
        </ProviderWrapper>
      </body>
    </html>
  );
}
